version: "3.8"  

services:
  
  # Monitroing services

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.prometheus.rule=Host(`prometheus.local`)"
        - "traefik.http.services.prometheus.loadbalancer.server.port=9090"
    networks:
      - net_public

  grafana:
    image: grafana/grafana:12.1
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "admin"
    volumes:
      - grafana_data:/var/lib/grafana
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.grafana.rule=Host(`grafana.local`)"
        - "traefik.http.services.grafana.loadbalancer.server.port=3000"
    networks:
      - net_public
  
  advisor:
    image: google/advisor:latest
    environment:
      PROMETHEUS_URL: http://prometheus:9090
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.advisor.rule=Host(`advisor.local`)"
        - "traefik.http.services.advisor.loadbalancer.server.port=8080"
    networks:
      - net_public


volumes:
  prometheus_data:
  grafana_data: