version: "3.8"  

services:
  
  # Monitoring services

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.prometheus.rule=Host(`prometheus.local`)"
        - "traefik.http.services.prometheus.loadbalancer.server.port=9090"
    networks:
      - demo_net_public

  grafana:
    image: grafana/grafana:12.1
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "admin"
    volumes:
      - grafana_data:/var/lib/grafana
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.grafana.rule=Host(`grafana.local`)"
        - "traefik.http.services.grafana.loadbalancer.server.port=3000"
    networks:
      - demo_net_public
  
  # cAdvisor service : Docker container metrics (cpu, mem ... of each container )
  advisor:
    image: gcr.io/cadvisor/cadvisor
    environment:
      PROMETHEUS_URL: http://prometheus:9090
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.advisor.rule=Host(`advisor.local`)"
        - "traefik.http.services.advisor.loadbalancer.server.port=8080"
    networks:
      - demo_net_public
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /sys/fs/cgroup:/sys/fs/cgroup:ro 
  
  # Node Exporter service : host metrics (cpu, mem ... of the host)
  node-exporter:
    image: prom/node-exporter:latest
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
    networks:
      - demo_net_public
    ports:
      - "9100:9100"   # optional, only if you want direct access
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.rootfs=/rootfs'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'

volumes:
  prometheus_data:
  grafana_data:

networks:
  demo_net_public:
    external: true