version: "3.8"

services:
  # traefik service
  traefik:
    image: traefik:v2.11
    command:
      - "--providers.docker.swarmmode=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      # enable Traefik dashboard
      - "--api.dashboard=true"
      - "--api.insecure=true"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    deploy:
      placement:
        constraints:
          - node.role == manager
    networks:
      - net_public
  
  # node app service
  node:
    image: 192.168.56.101:5000/swarm/node-app:v2
    environment:
      VALKEY_HOST: valkey
      LIST_KEY: swarm:entries
      MAX_ITEMS: 5
    deploy:
      replicas: 2
      update_config:
        parallelism: 1       # number of containers to update at a time
        delay: 10s           # delay between updating batches
        order: start-first   # or stop-first
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.labels.role == worker
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.node.rule=Host(`nodeapp.local`)"
        - "traefik.http.services.node.loadbalancer.server.port=3000"
    networks:
      - net_public


  # node writer service
  app_writer:
    image: 192.168.56.101:5000/swarm/node-writer:v1
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.labels.role == worker
      restart_policy:
        condition: none   # IMPORTANT
    environment:
      VALKEY_HOST: valkey
      BATCH_SIZE: 5 # number of records to write in each batch
      INTERVAL_MS: 1000 # 1 second
      STOP_AFTER_MS: 600000  # 10 minute
    networks:
      - net_public

    
  # symfony service
  symfony:
    image: 192.168.56.101:5000/swarm/symfony-app:v0
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.labels.role == worker
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.symfony.rule=Host(`symfony.local`)"
        - "traefik.http.services.symfony.loadbalancer.server.port=8000"
    networks:
      - net_public

  # Valkey service (Redis fork)
  valkey:
    image: valkey/valkey:7
    command: ["valkey-server", "--appendonly", "yes"]
    volumes:
      - valkey_data:/data
    deploy:
      placement:
        constraints:
          - node.role == manager    # keep Valkey in the manager node only
    networks:
      - net_public
  
volumes:
  valkey_data:

networks:
  net_public:
    driver: overlay
  # internal:
  #   driver: overlay
  #   internal: true